export const ADD = {
  VERSION: "ADD_VERSION",
  PLATFORM: "ADD_PLATFORM",
  ENVIRONMENT: "ADD_ENVIRONMENT",
  CONFIG: "ADD_CONFIG"
}
export const DELETE = {
  VERSION: "DELETE_VERSION",
  PLATFORM: "DELETE_PLATFORM",
  ENVIRONMENT: "DELETE_ENVIRONMENT"
}
export const SELECT = {
  VERSION: "SELECT_VERSION",
  PLATFORM: "SELECT_PLATFORM",
  ENVIRONMENT: "SELECT_ENVIRONMENT",
  PARAMETRE: "SELECT_PARAMETRE",
}

export const DESELECT = {
  PARAMETRE: "DESELECT_PARAMETRE"
}

export const FETCH = {
  VERSIONS: "FETCH_VERSION",
  PLATFORMS: "FETCH_PLATFORMS",
  ENVIRONMENTS: "FETCH_ENVIRONMENTS",
  CONFIGS: "FETCH_CONFIGS",
  PROFILE: "FETCH_PROFILE",
  CATEGORYS: "FETCH_CATEGORYS"
}

export const SHOW = {
  MODAL: {
    DASHBOARD_ADDING: "SHOW_MODAL_DASHBOARD_ADDING",
    EDIT_CONFIG: "SHOW_MODAL_EDIT_CONFIG",
    PARAMETRES: "SHOW_MODAL_PARAMETRES",
  }
}

export const HIDE = {
  MODAL: {
    DASHBOARD_ADDING: "HIDE_MODAL_DASHBOARD_ADDING",
    EDIT_CONFIG: "HIDE_MODAL_EDIT_CONFIG",
    PARAMETRES: "HIDE_MODAL_PARAMETRES"
  }
}

export const ACTIVE = {
  SELECT_MODE: "ACTIVE_SELECT_MODE"
}

export const DEACTIVE = {
  SELECT_MODE: "DEACTIVE_SELECT_MODE"
}

export const TOGGLE = {
  SELECT_MODE: "TOGGLE_SELECT_MODE"
}

export const START = {
  LOADING: "START_LOADING"
}

export const END = {
  LOADING: "END_LOADING"
}

export const SET = {
  TEMPO_PROFILE_NAME: "SET_TEMPO_PROFILE_NAME",
  PREVIOUS_SELECTED: "SET_PREVIOUS_SELECTED",
  COLOR: "SET_COLOR"
}

export const RESET = {
  COLOR: "RESET_COLOR"
}

export type action = {
  type: string,
  payload: any
}